### ISSUE TITLE
Undefined array key "doc" in TYPO3 V11 and News V11

### ISSUE THREAD

**Issue by yavivo** [nitsan-technologies/ns_news_advancedsearch#17]
Hi, I am encountering an error after installing (Composer Installation) the extension, and nothing appears in the News Plugin.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "doc" in /var/www/html/vendor/nitsan/ns-news-advancedsearch/Classes/Utility/ClassCacheManager.php line 187 | TYPO3\CMS\Core\Error\Exception thrown in file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php in line 137. 

Thank you & best Regards
Aji

**Comment by nitsan-technologies** [comment]
Hello @yavivo 

Thank you for reporting the issue, and we apologize for the inconvenience.

The error you're encountering seems to be related to an older version of the extension. We have addressed this in the latest release. Please update to the latest version, which should resolve the problem.

If the issue persists after updating, feel free to provide more details, and we'll be happy to assist further.

Thank you for your patience and support!

Best regards,
Team NITSAN
