### ISSUE TITLE
Implement subject search field

### ISSUE THREAD

**Issue by klodeckl** [nitsan-technologies/ns_news_advancedsearch#4]
Hello,

it would be great to additionally use the classic subject field (where the search fields can be chosen).

**Comment by nitsan-technologies** [comment]
Hello @klodeckl 
Greetings of the day!

Thank you very much for your suggestion. We didn't understand your exact need for this. We already have taken two important and required fields for the search. Maybe you can share some references and more details about your need.
Btw, If you are already a programmer and can develop such a need and want to contribute then we are open to receive a PR and we will merge your contributed code.

Waiting for your reply here. Have a great day head.

Thanks!
Team NITSAN
