### ISSUE TITLE
Search Results Not Showing

### ISSUE THREAD

**Issue by Krishna-nitsan** [nitsan-technologies/ns_news_advancedsearch#8]
Hi,

I've checked this extension and Found news Results not showing!
Test Environment:
Typo3 V11.5.13
php V7.4
ns_news_advancedsearch v2.0.3

Please Fix this!
Thanks!

![news_Advance_search](https://user-images.githubusercontent.com/117087880/210213129-53253320-a836-42a0-8889-9457325cfd3c.png)

**Comment by nitsan-technologies** [comment]
Hi, @Krishna-nitsan 

Thank you for your report, and we apologize for the delayed response.

The issue with news results not showing has been resolved in the latest version. We recommend updating to the latest version to ensure everything works smoothly.

If you experience any issues moving forward, feel free to reach out.

Thank you for your understanding and continued support!
